title: Czech-IT!
description: Linguistic corpus of native Czech learners acquiring Italian language
theme: 
github:
  - is_project_page: true
show_downloads: true
github_username: Czech-IT
gems: 
  - jekyll-feed
